---
services:
  cells:
    image: pydio/cells:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - cellsdir:/var/cells
      - data:/var/cells/data
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: password
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadbdird:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

volumes:
  data: {}
  cellsdir: {}
  mariadbdird: {}

