User tinyproxy
Group tinyproxy
Port 8888
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogFile "/var/log/tinyproxy/tinyproxy.log"
Syslog On
LogLevel Info
PidFile "/run/tinyproxy/tinyproxy.pid"
MaxClients 100
ViaProxyName "tinyproxy"
Filter "/etc/tinyproxy/whitelist"
FilterURLs Off
FilterType ere
FilterCaseSensitive Off
FilterDefaultDeny Yes

