# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "serafin-tech/debian13"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 8888, host: 8888

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "tinyproxy"
    vb.memory = "512"
    vb.cpus = 1
  end

  config.vm.provision "shell", run: "once", inline: <<-SHELL
    apt-get update
  SHELL

  config.vm.provision "shell", path: "provision_script.sh"

  config.ssh.private_key_path = "/home/serafin/.ssh/id_ed25519"
end
